apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-pull-secret
  namespace: monitoring
spec:
  encryptedData:
    .dockerconfigjson: <generate with: kubectl create secret docker-registry registry-pull-secret --docker-server=your-registry --docker-username=your-username --docker-password=your-token --namespace=monitoring --dry-run=client -o yaml | kubeseal --controller-name=sealed-secrets --controller-namespace=kube-system --format yaml>
  template:
    metadata:
      name: registry-pull-secret
      namespace: monitoring
    type: kubernetes.io/dockerconfigjson