apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: huawei-lte-secret
  namespace: monitoring
spec:
  encryptedData:
    username: <generate with: echo -n 'your-username' | kubectl create secret generic huawei-lte-secret --dry-run=client --from-file=username=/dev/stdin -o yaml | kubeseal --format yaml>
    password: <generate with: echo -n 'your-password' | kubectl create secret generic huawei-lte-secret --dry-run=client --from-file=password=/dev/stdin -o yaml | kubeseal --format yaml>
  template:
    metadata:
      name: huawei-lte-secret
      namespace: monitoring